version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cbmm-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP4ssword!"
      MSSQL_PID: "Developer"   # o "Express" / "Standard" seg√∫n el caso
      TZ: "UTC"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mssql-data:
    driver: local
